

def get_available_models():
    models = {
        # "Qwen/Qwen3-30B-A3B" : True,
        # "Qwen/Qwen3-32B" : True,
        # "Qwen/Qwen3-14B" : True,
        # "Qwen/Qwen3-8B" : True,
        # "Qwen/Qwen3-235B-A22B" : True,
        # "THUDM/GLM-Z1-32B-0414" : True,
        # "THUDM/GLM-4-32B-0414" : True,
        # "THUDM/GLM-Z1-Rumination-32B-0414" : True,
        # "THUDM/GLM-4-9B-0414" : True,
        # "Qwen/QwQ-32B" : True,
        # "Pro/deepseek-ai/DeepSeek-R1" : False,
        # "Pro/deepseek-ai/DeepSeek-V3" : False,
        # "deepseek-ai/DeepSeek-R1" : True,
        "deepseek-ai/DeepSeek-V3" : True,
        # "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B" : True,
        # "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B" : True,
        # "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B" : True,
        # "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B" : True,
        # "Pro/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B" : False,
        # "Pro/deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B" : False,
        # "deepseek-ai/DeepSeek-V2.5" : True,
        # "Qwen/Qwen2.5-72B-Instruct-128K" : True,
        # "Qwen/Qwen2.5-72B-Instruct" : True,
        # "Qwen/Qwen2.5-32B-Instruct" : True,
        # "Qwen/Qwen2.5-14B-Instruct" : True,
        # "Qwen/Qwen2.5-7B-Instruct" : True,
        # "Qwen/Qwen2.5-Coder-32B-Instruct" : True,
        # "Qwen/Qwen2.5-Coder-7B-Instruct" : True,
        # "Qwen/Qwen2-7B-Instruct" : True,
        # "Qwen/Qwen2-1.5B-Instruct" : True,
        # "Qwen/QwQ-32B-Preview" : True,
        # "TeleAI/TeleChat2" : False,
        # "THUDM/glm-4-9b-chat" : True,
        # "Vendor-A/Qwen/Qwen2.5-72B-Instruct" : False,
        # "internlm/internlm2_5-7b-chat" : True,
        # "internlm/internlm2_5-20b-chat" : True,
        # "Pro/Qwen/Qwen2.5-7B-Instruct" : True,
        # "Pro/Qwen/Qwen2-7B-Instruct" : True,
        # "Pro/Qwen/Qwen2-1.5B-Instruct" : True,
        # "Pro/THUDM/chatglm3-6b" : False,
        # "Pro/THUDM/glm-4-9b-chat" : True,
    }
    return models
